<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.9.2 on win32)" generated="20210308 23:58:14.103" rpa="false">
<suite id="s1" name="Login" source="D:\Ines\Curso\Robot\parodify\login.robot">
<test id="s1-t1" name="Login com sucesso">
<kw name="Open Browser">
<arguments>
<arg>http://parodify.herokuapp.com/users/sign_in</arg>
<arg>chromium</arg>
</arguments>
<msg timestamp="20210308 23:58:14.290" level="FAIL">No keyword with name 'Open Browser' found.</msg>
<status status="FAIL" starttime="20210308 23:58:14.289" endtime="20210308 23:58:14.290"></status>
</kw>
<status status="FAIL" starttime="20210308 23:58:14.287" endtime="20210308 23:58:14.290" critical="yes">No keyword with name 'Open Browser' found.</status>
</test>
<doc>Teste da tela de login</doc>
<status status="FAIL" starttime="20210308 23:58:14.105" endtime="20210308 23:58:14.293"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Login">Login</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210308 23:58:14.282" level="ERROR">Error in file 'D:\Ines\Curso\Robot\parodify\login.robot' on line 3: Initializing test library 'Browser' with no arguments failed: Couldn't execute node. Please ensure you have node.js installed and in PATH. See https://nodejs.org/ for instructions. Original error is [WinError 2] O sistema n√£o pode encontrar o arquivo especificado
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\Browser\browser.py", line 665, in __init__
    self.playwright = Playwright(self, enable_playwright_debug)
  File "c:\python39\lib\site-packages\Browser\playwright.py", line 42, in __init__
    self.ensure_node_dependencies()
  File "c:\python39\lib\site-packages\Browser\playwright.py", line 56, in ensure_node_dependencies
    raise RuntimeError(</msg>
</errors>
</robot>
